### PR TITLE
fix: deep cloning state and original drp

### LINKED ISSUE #293: Fix drp cloning
Currently canvas example does not run, when trying to paint a pixel it throws an error (screenshot below).
image

This is because when deep cloning the drp with the current approach
```ts
		this.originalDRP = Object.create(
			Object.getPrototypeOf(drp),
			Object.getOwnPropertyDescriptors(structuredClone(drp)),
		);
```
comparing `drp` and `originalDRP`, the cloning converts Pixel objects to just objects with the functions, both logged below
image

### PR DESCRIPTION
**Pull request by JanLewDev**
Introduce using `cloneDeep` from `es-toolkit` to deeply clone nested objects with all functions, which makes canvas example work again and closes #293

### CODE REVIEW

File: packages/object/src/index.ts [hunk 1]
```diff
@@ -13,6 +13,7 @@ import { ObjectSet } from "./utils/objectSet.js";
 
 export * as ObjectPb from "./proto/drp/object/v1/object_pb.js";
 export * from "./hashgraph/index.js";
+import { clone, cloneDeep } from "es-toolkit";
```
Comment (trungnotchung) [inline packages/object/src/index.ts:16]:
```suggestion
import { cloneDeep } from "es-toolkit";
```
remove unused import

**Review by d-roak — APPROVED** [review]
Pre-approving
Apply trung comment

**Review by trungnotchung — APPROVED** [review]
lgtm

**Review by anhnd350309 — APPROVED** [review]
